.TH DERPGP: "1" "November 2017" "derpgp: DERPGP v0\&.0\&.1" "User Commands"

.SH "NAME"
derpgp \- derp.

.SH "SYNOPSIS"
.sp
.nf
\fIderpgp\fR [\-hv] [\-i\fI“<int.gpg>”\fR] [-o\fI“<out.pem>”\fR]
.fi

.SH "DESCRIPTION"
.sp
boop.
.fi

.SH "USAGE"
.sp
oink.
.fi

.SS "OPTIONS"
.sp
Command line options:
.fi

.HP
\fB\-h\fR,\fB\-\-help\fR:		Show help/usage information
.HP
\fB\-i\fR,\fB\-\-input\fR:		ame of the file to use for input
.HP
\fB\-o\fR,\fB\-\-output\fR:		Name of the file to output source to
.HP
\fB\-v\fR,\fB\-\-version\fR:		Show version information
.fi

.SH "NOTES"
.sp
Please direct any bug/issue reports, as well as any feature requests, to <\fIhttps://github\&.com/alyptik/derpgp\fR>
.fi

.SH "AUTHORS"
.ie n \{\
 \h'-04'\(bu\h'+03'\c \&.\}
.el \{\
.sp -1
.IP \(bu 2\&.3
.\}
Joey Pabalinas <\fIalyptik@protonmail\&\&.com\fR>
.fi
.ie n \{\
 \h'-04'\(bu\h'+03'\c \&.\}
.el \{\
.sp -1
.IP \(bu 2\&.3
.\}
Santiago Torres <\fIsangy@riseup\&\&.net\fR>
.fi
