.TH derpgp: "7" "June 2017" "derpgp: derpgp v1.2.1" "User Commands"

.SH "NAME"
derpgp - derpgp

.SH "SYNOPSIS"
.sp
.nf
\fIderpgp\fR [\-hv] [\-o\fI<output.c>\fR]
.fi

.SH "DESCRIPTION"
.sp
derpgp
general algorithm exploration.

.SH "USAGE"
.sp
derpgp

.SS "COMMANDS"
.sp
derpgp

.SS "OPTIONS"
.sp
Command line options:

.HP
\fB\-h\fR,\fB\-\-help\fR:	Show help/usage information.
.HP
\fB\-v\fR,\fB\-\-version\fR:	Show version information.
.HP
\fB\-o\fR:			Name of the file to output source to.

.SH "AUTHOR"
.sp
Joey Pabalinas <alyptik@protonmail.org>

.SH "NOTES"
.sp
https://github.com/alyptik/<tempalte>
